---
title: "SOData"
author: "John Fay"
date: "February 5, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
## Loading the data
```{r Load and Merge Raw Data Files}
getwd()
library(tidyverse)
library(modelr)
library(broom)

#Read in data files
trial1 <- read_csv('./Data/Raw/Box2_2Feb-1051.csv')
trial2 <- read_csv('./Data/Raw/Box2_5Feb-804pm.csv')
trial3 <- read_csv('./Data/Raw/box 2_2fev-1040fix.csv')
trial4 <- read_csv('./Data/Raw/Box2_6Feb730.csv')
trial5 <- read_csv('./Data/Raw/Box2_6Feb804.csv')
trial6 <- read_csv('./Data/Raw/Box2_9Feb930.csv')
trial7 <- read_csv('./Data/Raw/Box2_9Feb1000.csv')
trial8 <- read_csv('./Data/Raw/Box2_17Feb01.csv')
trial9 <- read_csv('./Data/Raw/Box2_17Feb02.csv')
trial0 <- read_csv('./Data/Raw/Box2_17Feb03.csv')

#functon for tidying tables
tidyTable <- function (table,TrialName){
  colnames(table) <- c("Time","Temp")
  table <- table %>% 
    mutate(TName = TrialName) %>% 
    mutate(InitialT = max(table$Temp)) %>% 
    mutate(Trial = paste0(TrialName,' (',max(table$Temp),"°C)")) %>% 
    mutate(TrialX = paste0(TrialName,' (',max(table$Temp),"-",min(table$Temp),"°C)"))
  return (table)
}

trial1 <- tidyTable(trial1,"T1")
trial2 <- tidyTable(trial2,"T2")
trial3 <- tidyTable(trial3,"T3")
trial4 <- tidyTable(trial4,"T4")
trial5 <- tidyTable(trial5,"T5")
trial6 <- tidyTable(trial6,"T6")
trial7 <- tidyTable(trial7,"T7")
trial8 <- tidyTable(trial8,"T8")
trial9 <- tidyTable(trial9[,3:4],"T9")
trial0 <- tidyTable(trial0[,5:6],"T0")

#Combine data
trials <- rbind(trial0, trial1, trial2, trial3, trial4, trial5, trial6, trial7, trial8, trial9)

#Remove trial tibbles
remove(trial1, trial2, trial3, trial4, trial5, trial6, trial7, trial8, trial9, trial0)

#Write to csv
write.csv(trials,"./Data/Processed/AllTrials.csv",row.names = FALSE)

```

##Extract a subset of points
```{r}
#Extract points for every 2.5 minutes (10 samples)
trialsX <- trials %>% 
  filter(Time %in% seq(0,25,2.5))

#Write to csv
write.csv(trialsX,"./Data/Processed/AllTrials_10.csv",row.names = FALSE)
```

##Plotting the data
```{r Plot All Trials on one plot}
p = ggplot(trialsX, aes(x=Time,y=Temp,color=as.factor(TrialX))) + 
  geom_line() + 
  geom_point(size=3) + 
  ylab('Temperature (°C)') +
  xlab('Time (minutes)') +
  xlab("Elapsed Time (min)") + 
  ylab("Internal Beaker Water Temp (°C)") + 
  labs(col="Trial (Init.T°-End T°)") + 
  ggtitle("Internal Beaker Temp. vs. Elapsed Time",
        subtitle = "Team: Voyager Academy B (JV)\nMembers: Amelia Fay & Eisley Jantz") +
  scale_y_continuous(breaks = seq(54,78,2),limits = c(53,78)) +
  #scale_color_brewer(type='qual',palette = 'Paired') +
  theme(legend.position = c(0.87,0.73),
        legend.text = element_text(size=8),
        legend.title = element_text("Initial Temp. (°C)"))
p
ggsave("AllTrials.jpg",
       width = 8.5, height = 6.5,
       plot = p,
       path = './Figures')
```

##Individual plots
```{r Plot Graphs}
for (TrialName in unique(trialsX$Trial)) {
  #Isolate the trial records
  trialData <- trialsX %>% filter(Trial == TrialName)
  #Get values
  TName = first(trialData$TName)
  InitT = first(trialData$InitialT)
  figName = paste('./Figures/',TName,".jpg")
  #Create the title
  plotTitle <- paste("Internal Beaker Temp. vs. Elapsed Time\nTrial: ",TName, ", Initial Temp: ",InitT, '°C')
  #Plot
  ggplot(trialData, aes(x=Time,y=Temp),color='grey')  +
    geom_line(color='red') + 
    geom_point(color='red',size=3) +
    ggtitle(plotTitle,
            subtitle = "Team: Voyager Academy\nMembers: Amelia Fay & Eisley Jantz") +
    xlab("Elapsed Time (min)") + 
    ylab("Internal Beaker Water Temp (°C)") + 
    scale_y_continuous(breaks = seq(56,74,2),limits = c(56,74)) 
    #theme(legend.position = c(0.8,0.8),
    #      plot.title = element_text(hjust=0.5,vjust=-1,face='bold'))
  ggsave(figName)
} 
```

## Summarise the data and generate a model
```{r Summarising the data}
trial_summary <- trials %>% 
  group_by(Trial) %>% 
  summarise(startT = max(Temp),
            endT = min(Temp)) %>% 
  mutate(TDiff = startT - endT)
head(trial_summary)
write.csv(trial_summary, "./Data/Processed/DataSummary.csv")
```

```{r}
#Compute the linear model
theModel <- lm(endT ~ startT, trial_summary)
#Tidy the outputs
theModel.output <- tidy(theModel)
#Extract model coefficients
y.intercept = theModel.output$estimate[1]
slope <- theModel.output$estimate[2]

#Apply the model as a function
tFun = function(startT) {
  endT = startT * slope + y.intercept
  return(endT)
}

#Extend function
xFun <- function(tNum,startT) {
  tName <-  paste0(tNum," (",startT,"°C)")
  endT <-  round(startT * slope + y.intercept, 2)
  TDiff  <-  startT - endT
  return (list(tName,startT,endT,TDiff,endT))
}


trial_summary <- trial_summary %>% 
  mutate(expectedTemp = theModel$fitted.values) 
write.csv(trial_summary,'summary.csv',row.names = FALSE)


```

```{r Plot Fitted Values}
funcT = paste0('End T = (Start T * ',round(slope,3),') + ',round(y.intercept,3))

ggplot(trial_summary) + 
  geom_point(aes(x=startT,y=endT, color=Trial),size=3)  + 
  geom_line(aes(x=startT,y=expectedTemp), color='blue') +
  #geom_smooth(method='lm',aes(x=startT,y=endT)) + 
  xlab("Initial Temperature (°C)") +
  ylab("Ending Temperature (°C)") +
  geom_text(x=61.5,y=63,label=funcT,hjust=0,color = 'blue') +
  ggtitle("Ending vs Intial Temperature after 25 minutes",
            subtitle = "Team: Voyager Academy B (JV)\nMembers: Amelia Fay & Eisley Jantz") + 
  scale_x_continuous(breaks = seq(60,75,0.5)) +
  scale_y_continuous(breaks=seq(50,63,0.5)) +
  theme(axis.text.x = element_text(angle=45,hjust=1),
        legend.text = element_text(size=8),
        legend.position = c(0.85,0.35),
        legend.title = element_text("Trial (Init °C)"))

ggsave("EndVsInit.jpg",
       width = 8.5, height = 6.5,
       path = './Figures')

```

